options(repos = c("CRAN" = "http://cran.ma.imperial.ac.uk"))
install.packages(c("devtools","shiny"))
library(devtools)
source("http://www.bioconductor.org/biocLite.R")
biocLite(c("Biobase","ggplot2","dplyr","tidyr","gridExtra","heatmap.plus","RColorBrewer","party","survival","knitr","broom","WGCNA","gplots"))
install_github("crukci-bioinformatics/prostateCancerTaylor")
install_github("crukci-bioinformatics/prostateCancerCamcap")
install_github("crukci-bioinformatics/prostateCancerStockholm")
install_github("crukci-bioinformatics/prostateCancerGrasso")
install_github("crukci-bioinformatics/prostateCancerVarambally")

